# Railway Nixpacks configuration for Python + Chrome
[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'chromium', 'chromedriver']

[phases.install] 
cmds = [
  'python -m pip install --upgrade pip',
  'python -m pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'python main.py'
